
UPDATE public.games SET categories = CASE title
  WHEN 'GTA V' THEN ARRAY['hits']
  WHEN 'GTA VI' THEN ARRAY['new','hits','exclusive']
  WHEN 'FIFA 26' THEN ARRAY['new','hits','coop','sports']
  WHEN 'EA FC 25' THEN ARRAY['coop','hits','sports']
  WHEN 'Mortal Kombat 1' THEN ARRAY['coop','hits']
  WHEN 'UFC 5' THEN ARRAY['coop','sports']
  WHEN 'Call of Duty MW III' THEN ARRAY['hits','coop']
  WHEN 'Spider-Man 2' THEN ARRAY['exclusive','hits']
  WHEN 'God of War Ragnarok' THEN ARRAY['exclusive','hits']
  WHEN 'The Last of Us Part II' THEN ARRAY['exclusive','horror']
  WHEN 'Horizon Forbidden West' THEN ARRAY['exclusive']
  WHEN 'Gran Turismo 7' THEN ARRAY['racing','exclusive']
  WHEN 'Need for Speed Unbound' THEN ARRAY['racing']
  WHEN 'F1 24' THEN ARRAY['racing','new']
  WHEN 'Crash Bandicoot 4' THEN ARRAY['kids','coop']
  WHEN 'Sackboy: A Big Adventure' THEN ARRAY['kids','coop','exclusive']
  WHEN 'Minecraft' THEN ARRAY['kids','coop']
  WHEN 'LEGO Star Wars' THEN ARRAY['kids','coop']
  WHEN 'Ratchet & Clank' THEN ARRAY['kids','exclusive']
  WHEN 'Resident Evil 4 Remake' THEN ARRAY['horror','hits']
  WHEN 'Resident Evil Village' THEN ARRAY['horror']
  WHEN 'Alan Wake 2' THEN ARRAY['horror','new']
  WHEN 'Dead Space Remake' THEN ARRAY['horror']
  WHEN 'It Takes Two' THEN ARRAY['coop','hits']
  WHEN 'A Way Out' THEN ARRAY['coop']
  WHEN 'Overcooked! 2' THEN ARRAY['coop','kids']
  WHEN 'Mortal Kombat XL' THEN ARRAY['coop']
  WHEN 'Tekken 8' THEN ARRAY['new','coop']
  WHEN 'Street Fighter 6' THEN ARRAY['coop','new']
  WHEN 'Hogwarts Legacy' THEN ARRAY['hits']
  WHEN 'Elden Ring' THEN ARRAY['hits']
  WHEN 'Cyberpunk 2077' THEN ARRAY['hits']
  WHEN 'Assassin''s Creed Shadows' THEN ARRAY['new']
  WHEN 'Death Stranding 2' THEN ARRAY['new','exclusive']
  WHEN 'Returnal' THEN ARRAY['exclusive','horror']
  WHEN 'Demon''s Souls' THEN ARRAY['exclusive']
  ELSE categories
END
WHERE categories = '{}';
